In [59]:
import numpy as np

marks=np.array([1,2,3,5,6,7,8,9,9])
print(marks)
print(type(marks))

<class 'SyntaxError'>: invalid syntax (<ipython-input-59-abf8a2ab9ed6>, line 2)

In [9]:
#3d array basically for image processing

image = np.array([[[255, 0, 0],    # pixel 1 - red
                   [0, 255, 0]],   # pixel 2 - green
                  [[0, 0, 255],    # pixel 3 - blue
                   [255, 255, 0]]]) # pixel 4 - yellow
print(image)  # (2, 2, 3)

[[[255   0   0]
  [  0 255   0]]

 [[  0   0 255]
  [255 255   0]]]


In [12]:
#shape->defines rows and the colmn

marks=np.array([[1,2,3],[5,6,7],[8,9,9]])
print(marks)
print(marks.shape)

[[1 2 3]
 [5 6 7]
 [8 9 9]]
(3, 3)


In [19]:
#0 array / NUll matrix
#5 colmns and 0 rows by default 
a=np.zeros(5)
a=np.zeros((3,4)) #3 rows and 4 colmns always in tuple
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
#identity matrix
a=np.ones(9)
print(a

m=np.ones((3,4))
print(m)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [55]:
#ARANGE()

#sequential arrangement
a=np.arange(7)
print(a)

#(start,stop,gap)
a=np.arange(1,101,7)
print(a)

[0 1 2 3 4 5 6]
[ 1  8 15 22 29 36 43 50 57 64 71 78 85 92 99]


In [35]:
#LINSPACE()
#EQUALLIY DISTRIBUTION OF NUMBER (START,STOP,PARTICITION)
a=np.linspace(1,9,10)
print(a)

[1.         1.88888889 2.77777778 3.66666667 4.55555556 5.44444444
 6.33333333 7.22222222 8.11111111 9.        ]


In [45]:
#random integer/matric
a=np.random.randint(0,5,6)
print(a)

b = np.random.rand(3, 3)
print(b)

[0 3 2 4 3 4]
[[0.10047876 0.25595067 0.20315048]
 [0.08973223 0.3443109  0.04347701]
 [0.42277752 0.61176626 0.06205152]]


In [50]:
#np.full() — ek specific value se bharo

a=np.full(3,7) #3=col,7 value
print(a)

#matrix
a=np.full((3,6),9)
print(a)


[7 7 7]
[[9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]]


In [58]:
import numpy as np

# 100 students ka result system banana hai
# Pehle sab ko 0 marks se shuru karo
result = np.zeros(100)

# Exam numbers 1 se 100 tak
roll_numbers = np.arange(1, 101,6)

# Passing marks — 33 se 100 ke beech 10 points
passing = np.linspace(33, 100, 10)

print("Results shape:", result.shape)
print("Roll numbers:", roll_numbers[:5])  # pehle 5
print("Passing criteria:", passing)

Results shape: (100,)
Roll numbers: [ 1  7 13 19 25]
Passing criteria: [ 33.          40.44444444  47.88888889  55.33333333  62.77777778
  70.22222222  77.66666667  85.11111111  92.55555556 100.        ]
